# Generated by GitHub Copilot on 2025-11-06
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.TextField(blank=True)),
                ('antecedentes_medicos', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('possui_diabetes', models.BooleanField(default=False)),
                ('possui_hipertensao', models.BooleanField(default=False)),
                ('cardiopatia', models.BooleanField(default=False)),
                ('asma', models.BooleanField(default=False)),
                ('hemorragias', models.BooleanField(default=False)),
                ('anestesia_reacao', models.BooleanField(default=False)),
                ('fuma', models.BooleanField(default=False)),
                ('gravida', models.BooleanField(default=False)),
                ('pressao_sistolica', models.PositiveIntegerField(blank=True, null=True)),
                ('pressao_diastolica', models.PositiveIntegerField(blank=True, null=True)),
                ('batimentos', models.PositiveIntegerField(blank=True, null=True)),
                ('outros', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='pacientes.paciente')),
            ],
            options={},
        ),
        migrations.AddIndex(
            model_name='anamnese',
            index=models.Index(fields=['paciente'], name='anam_paciente_idx'),
        ),
    ]
