# Generated by Django 4.2.26 on 2025-11-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_documento'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='anamnese',
            new_name='pacientes_a_pacient_2d94c4_idx',
            old_name='anam_paciente_idx',
        ),
        migrations.RenameIndex(
            model_name='documento',
            new_name='pacientes_d_pacient_3d1a35_idx',
            old_name='pacientes_d_paciente_',
        ),
        migrations.RenameIndex(
            model_name='documento',
            new_name='pacientes_d_criado__b77132_idx',
            old_name='pacientes_d_criado__',
        ),
    ]
