# Generated by ChatGPT
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0004_rename_anam_paciente_idx_pacientes_a_pacient_2d94c4_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescricao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profissional", models.CharField(blank=True, max_length=120)),
                ("cro", models.CharField(blank=True, max_length=30)),
                ("observacoes", models.TextField(blank=True)),
                ("itens", models.JSONField(default=list)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("paciente", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="prescricoes", to="pacientes.paciente")),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="prescricao",
            index=models.Index(fields=["paciente", "criado_em"], name="pacientes_paciente_criado_idx"),
        ),
    ]
