# Generated by Django 4.2.26 on 2025-11-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_prescricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('cpf_normalizado', models.CharField(blank=True, db_index=True, max_length=11)),
                ('telefone', models.CharField(max_length=32)),
                ('telefone_normalizado', models.CharField(db_index=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('novo', 'Nunca contatado'), ('enviado', 'Convite enviado'), ('falha', 'Falha no envio')], default='novo', max_length=20)),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConviteImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('origem', models.CharField(blank=True, max_length=120)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('importados', models.PositiveIntegerField(default=0)),
                ('atualizados', models.PositiveIntegerField(default=0)),
                ('ignorados', models.PositiveIntegerField(default=0)),
                ('erros', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConviteMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('falha', 'Falhou')], default='enviado', max_length=20)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RenameIndex(
            model_name='prescricao',
            new_name='pacientes_p_pacient_de6f26_idx',
            old_name='pacientes_paciente_criado_idx',
        ),
        migrations.AddField(
            model_name='convitemensagem',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='pacientes.convitecontato'),
        ),
        migrations.AddIndex(
            model_name='convitecontato',
            index=models.Index(fields=['status', 'ultima_mensagem_em'], name='pacientes_c_status_7263bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='convitecontato',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf_normalizado__isnull', False), models.Q(('cpf_normalizado', ''), _negated=True)), fields=('cpf_normalizado',), name='unique_convite_cpf'),
        ),
        migrations.AddConstraint(
            model_name='convitecontato',
            constraint=models.UniqueConstraint(condition=models.Q(('telefone_normalizado__isnull', False), models.Q(('telefone_normalizado', ''), _negated=True)), fields=('telefone_normalizado',), name='unique_convite_telefone'),
        ),
        migrations.AddIndex(
            model_name='convitemensagem',
            index=models.Index(fields=['status', 'criado_em'], name='pacientes_c_status_f379c2_idx'),
        ),
    ]
