# Generated by Django 5.2.7 on 2025-11-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidade', models.CharField(default='un', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['sku'], name='estoque_pro_sku_a5fad6_idx'), models.Index(fields=['nome'], name='estoque_pro_nome_116d41_idx')],
            },
        ),
    ]
