# Generated by Django 5.2.7 on 2025-11-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapa', models.JSONField(blank=True, default=dict)),
                ('anotacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['paciente'], name='odontograma_pacient_a7c17a_idx')],
            },
        ),
    ]
