# Generated by GitHub Copilot on 2025-11-05
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente', models.IntegerField()),
                ('procedimento', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='orcamentoitem',
            index=models.Index(fields=['orcamento'], name='orc_itens_orcamento_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentoitem',
            index=models.Index(fields=['dente'], name='orc_itens_dente_idx'),
        ),
    ]
