# Generated by GitHub Copilot on 2025-11-06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_alter_orcamentoitem_dente'),
    ]

    operations = []
