# Generated by Django 4.2.26 on 2025-11-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_orcamentoitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orcamentoitem',
            new_name='orcamentos__orcamen_5a8458_idx',
            old_name='orc_itens_orcamento_idx',
        ),
        migrations.RenameIndex(
            model_name='orcamentoitem',
            new_name='orcamentos__dente_93b72f_idx',
            old_name='orc_itens_dente_idx',
        ),
        migrations.AlterField(
            model_name='orcamentoitem',
            name='dente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
