# Generated by GitHub Copilot on 2025-11-06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_rename_orc_itens_orcamento_idx_orcamentos__orcamen_5a8458_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoitem',
            name='dente',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
