# Generated by Django 4.2.26 on 2025-11-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_debito'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='debito',
            new_name='financeiro__pacient_6b2e7b_idx',
            old_name='financeiro__pacient_9e58ca_idx',
        ),
        migrations.RenameIndex(
            model_name='debito',
            new_name='financeiro__data_ve_076d46_idx',
            old_name='financeiro__data_ven_f3b5f9_idx',
        ),
    ]
